development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: grad_db
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: grad_db
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: grad_db
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock